[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "fow"
dynamic = ["version"]
description = "\nForward Over Wormhole provides bi-directional streaming data over secure and durable Dilated magic-wormhole connections. Secure communication with easy setup."
readme = "README.rst"
license.text = "MIT"
authors = [
    { name = "meejah", email = "meejah@meejah.ca" },
]
keywords = [
    "cryptography",
    "forwarding",
    "magic-wormhole",
    "private",
]
classifiers = [
    "Framework :: Twisted",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "click",
    "wormhole",
]

[project.optional-dependencies]
test = ["pytest"]
dev = ["twine", "sphinx"]

[project.scripts]
fow = "fow.cli:_entry"

[tool.hatch.version]
path = "src/fow/__init__.py"

#[tool.hatch.build.targets.sdist]
#include = [
#    "src",
#]
