[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "fow"
dynamic = ["version"]
description = "\nForward Over Wormhole pipes streaming data over Dilated Magic\nWormhole subchannels. Secure communication with easy setup"
readme = "README.rst"
license = "MIT"
authors = [
    { name = "meejah", email = "meejah@meejah.ca" },
]
keywords = [
    "cryptography",
    "forwarding",
    "magic-wormhole",
    "private",
]
classifiers = [
    "Framework :: Twisted",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "click",
]

[tool.hatch.version]
path = "fow/__init__.py"

[tool.hatch.build.targets.sdist]
include = [
    "/src",
]
